name: micro_timer
description: 'A new Flutter project.'

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  glossy: ^0.0.4
  flutter_hooks: ^0.20.5
  mesh_gradient: ^1.3.6
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  audioplayers: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  intl: ^0.19.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/sounds/
    - assets/animations/
  uses-material-design: true
